### ISSUE TITLE
Anaconda Prompt Issue and Guidewire Navigation Parameters

### ISSUE THREAD

**Issue by Metaphysicist0** [candi4/SofaGuidewireNav#22]
Great job!  I'm very sorry for experiencing issues with Anaconda Prompt on a Windows environment due to my unfamiliarity with sofa. When following the 'How to use' instructions, the prompt fails to load and freezes, causing it to exit. Additionally, I would greatly appreciate guidance on modifying the parameters of the guidewire navigation, specifically: Destination: How to set or modify the destination coordinates or settings? Implant control algorithms: How to adjust or customize the implant control algorithms to suit specific requirements? Printing: How to print the guidewire navigation data or reports? I believe that it would be very helpful for works in this area. Thanks a lot!

**Comment by candi4** [comment]
Thank you for using my repository.


> When following the 'How to use' instructions, the prompt fails to load and freezes, causing it to exit. 

Please show me the code and the error message. 
I suspect the freezing issue is likely related to communication between [SimServer.py](https://github.com/candi4/SofaGuidewireNav/blob/main/SofaGW/simulation/SimServer.py) and [SimClient.py](https://github.com/candi4/SofaGuidewireNav/blob/main/SofaGW/simulation/SimClient.py).
I've got the same issue when I first run this code in Windows 11. So I Added these lines:
https://github.com/candi4/SofaGuidewireNav/blob/87a5ae81e576942367e9e737e137263aea870f90/SofaGW/simulation/SimClient.py#L19-L22
I referred this: [Python's xmlrpc extremely slow: one second per call](https://stackoverflow.com/questions/14504450/pythons-xmlrpc-extremely-slow-one-second-per-call)


> Destination: How to set or modify the destination coordinates or settings?

You need to do it yourself using image processing. You can obtain a vessel image (red) and a guidewire image (blue) from `GetImage`.


> Implant control algorithms: How to adjust or customize the implant control algorithms to suit specific requirements? 

It's up to you. I’m using reinforcement learning for guidewire navigation.


> Printing: How to print the guidewire navigation data or reports?

You can obtain data from the image or SOFA simulation. I couldn't find a documentation explaining how to get data from SOFA via [SofaPython3](https://github.com/sofa-framework/SofaPython3). If you find it, please let me know.

**Comment by Metaphysicist0** [comment]
Many thanks for your great patience!

When I execute the following code on my Windows 10 OS:
```python
from SofaGW import SimController
sim = SimController(timeout=10, vessel_filename='vessel/phantom.obj')
```
A blue guidewire appears (but keeps still), the 3D vascular map is not visible and returned at status 1.

![7899e8ffc1f76a585fbbfe30716b39e](https://github.com/user-attachments/assets/9e2a2563-e95b-478a-b41b-55b52c8db5c3)
![179a6b960919a0c579ea58c6c9e9967](https://github.com/user-attachments/assets/71836be1-9156-45b8-85f4-009c4e40e374)

This issue persists even after implementing the modifications in SimClient.py. 

I am also working on RL for Guidewire Navigation via sofa, though still a beginner in this field. Let's keep in touch and collaborate on any issues that arise.

**Comment by candi4** [comment]
Could you copy and paste everything in the prompt?
And, which version of this repo are you using? I revised many things for a few months. If you downloaded my repo a long time ago, you have to download again. README is also changed.

**Comment by Metaphysicist0** [comment]
1.Prompt:
```
import SofaGW
from SofaGW import SimController
sim = SimController(timeout=10, vessel_filename='vessel/phantom.obj')
```

Output
```
free_port : 49622
E:\Anaconda3\envs\sofarl\lib\site-packages\SofaGW/_cache_
---------------------------------------
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: G:\SOFA_v23.06.00_Win64
Warning: environment variable SOFAPYTHON3_ROOT is empty. Trying to guess it.
Guessed SOFAPYTHON3_ROOT: G:\SOFA_v23.06.00_Win64\plugins\SofaPython3
Found Sofa.Helper.dll in G:\SOFA_v23.06.00_Win64\bin
Found SofaPython3.dll in G:\SOFA_v23.06.00_Win64\plugins\SofaPython3\bin
---------------------------------------
pygame 2.6.0 (SDL 2.28.4, Python 3.8.19)
Hello from the pygame community. https://www.pygame.org/contribute.html
[SimClient.py] Start SimClient.py
[SimClient.py] Connected
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/BeamAdapter.dll
[DEPRECATED] [SofaMiscCollision] SofaMiscCollision is deprecated. It will be removed at v23.06. Use Sofa.Component.Collision.Geometry, Sofa.Component.Collision.Detection.Intersection and Sofa.Component.Collision.Response.Contact instead.
[DEPRECATED] [SofaMiscCollision] If you are looking for OBB and Capsule-related components, please use the external plugin CollisionOBBCapsule.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Collision.Geometry.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Collision.Detection.Intersection.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Collision.Response.Contact.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaMiscCollision.dll
[DEPRECATED] [SofaConstraint] SofaConstraint is deprecated. It will be removed at v23.06. You may use Sofa.Component.Mapping.MappedMatrix, Sofa.Component.Constraint.Lagrangian.Model, Sofa.Component.Constraint.Lagrangian.Correction, Sofa.Component.Constraint.Lagrangian.Solver, Sofa.Component.AnimationLoop, Sofa.Component.Collision.Detection.Intersection and Sofa.Component.Collision.Response.Contact instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Mapping.MappedMatrix.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Constraint.Lagrangian.Model.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Constraint.Lagrangian.Correction.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Constraint.Lagrangian.Solver.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.AnimationLoop.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaConstraint.dll
[DEPRECATED] [SofaImplicitOdeSolver] SofaImplicitOdeSolver is deprecated. It will be removed at v23.06. Use Sofa.Component.ODESolver.Backward instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.ODESolver.Backward.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaImplicitOdeSolver.dll
[DEPRECATED] [SofaGeneralLinearSolver] SofaGeneralLinearSolver is deprecated. It will be removed at v23.06. Use Sofa.Component.LinearSolver.Iterative and Sofa.Component.LinearSolver.Direct instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.LinearSolver.Iterative.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.LinearSolver.Direct.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaGeneralLinearSolver.dll
[DEPRECATED] [SofaBoundaryCondition] SofaBoundaryCondition is deprecated. It will be removed at v23.06. You may use Sofa.Component.Constraint.Projective and Sofa.Component.MechanicalLoad instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Constraint.Projective.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.MechanicalLoad.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaBoundaryCondition.dll
[DEPRECATED] [SofaDeformable] SofaDeformable is deprecated. It will be removed at v23.06. Use Sofa.Component.SolidMechanics.Spring instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.SolidMechanics.Spring.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaDeformable.dll
[DEPRECATED] [SofaTopologyMapping] SofaTopologyMapping is deprecated;. It will be removed at v23.06. You may use Sofa.Component.Topology.Mapping and/or Sofa.Component.Mapping instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Topology.Mapping.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Mapping.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaTopologyMapping.dll
[DEPRECATED] [SofaOpenglVisual] SofaOpenglVisual is deprecated;. Use Sofa.GL.Component.Rendering2D, Sofa.GL.Component.Rendering3D and Sofa.GL.Component.Shader instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.GL.Component.Rendering2D.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.GL.Component.Rendering3D.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.GL.Component.Shader.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaOpenglVisual.dll
[DEPRECATED] [SofaMeshCollision] SofaMeshCollision is being deprecated;. It will be removed at v23.06. You may use Sofa.Component.Collision.Geometry, Sofa.Component.Collision.Detection.Intersection, Sofa.Component.Collision.Response.Mapper and Sofa.Component.Collision.Response.Contact instead.
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Collision.Response.Mapper.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/SofaMeshCollision.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.Collision.Detection.Algorithm.dll
[INFO]    [PluginManager] Loaded plugin: G:/SOFA_v23.06.00_Win64/bin/Sofa.Component.IO.Mesh.dll
>>> [ERROR]   [MeshOBJLoader(meshLoader)] File: 'C:\Users\YTL\vessel\phantom.obj' not found.
[ERROR]   [MeshOBJLoader(meshLoader)] Cannot read file 'C:\Users\YTL\vessel\phantom.obj'.
[WARNING] [InteractiveCamera(camera)] Too many missing parameters ; taking default ...
[WARNING] [InterventionalRadiologyController(m_ircontroller)] Parameter missmatch: According to the list of controlled instrument controlled. The number of potential beams: 180 exceed the number of degree of freedom in the MechanicalObject: 60. This could lead to unespected behavior.
[ERROR]   [InterventionalRadiologyController(m_ircontroller)] Case 1 should never happen ==> avoid using totalLengthIsChanging! xCurvAbs = 1 > prev_maxCurvAbs = 0 + threshold: 0.01

 | newCurvAbs: 0 1 6 11 16 21
 | modifiedCurvAbs: 0 1 1 6 11 16
 | previous nodeCurvAbs: 0
[ERROR]   [InterventionalRadiologyController(m_ircontroller)] Case 1 should never happen ==> avoid using totalLengthIsChanging! xCurvAbs = 1 > prev_maxCurvAbs = 0 + threshold: 0.01

 | newCurvAbs: 0 1 6 11 16 21
 | modifiedCurvAbs: 0 1 1 6 11 16
 | previous nodeCurvAbs: 0
[ERROR]   [InterventionalRadiologyController(m_ircontroller)] Case 1 should never happen ==> avoid using totalLengthIsChanging! xCurvAbs = 6 > prev_maxCurvAbs = 0 + threshold: 0.01

 | newCurvAbs: 0 1 6 11 16 21
 | modifiedCurvAbs: 0 1 1 6 11 16
 | previous nodeCurvAbs: 0
[ERROR]   [InterventionalRadiologyController(m_ircontroller)] Case 1 should never happen ==> avoid using totalLengthIsChanging! xCurvAbs = 11 > prev_maxCurvAbs = 0 + threshold: 0.01

 | newCurvAbs: 0 1 6 11 16 21
 | modifiedCurvAbs: 0 1 1 6 11 16
 | previous nodeCurvAbs: 0
[ERROR]   [InterventionalRadiologyController(m_ircontroller)] Case 1 should never happen ==> avoid using totalLengthIsChanging! xCurvAbs = 16 > prev_maxCurvAbs = 0 + threshold: 0.01

 | newCurvAbs: 0 1 6 11 16 21
 | modifiedCurvAbs: 0 1 1 6 11 16
 | previous nodeCurvAbs: 0
[WARNING] [AdaptiveBeamForceFieldAndMass(CatheterForceField)] buildStiffnessMatrix not implemented: for compatibility reason, the deprecated API (addKToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addKToMatrix has been replaced by buildStiffnessMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(GuideForceField)] buildStiffnessMatrix not implemented: for compatibility reason, the deprecated API (addKToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addKToMatrix has been replaced by buildStiffnessMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(CoilsForceField)] buildStiffnessMatrix not implemented: for compatibility reason, the deprecated API (addKToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addKToMatrix has been replaced by buildStiffnessMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(CatheterForceField)] buildMassMatrix not implemented: for compatibility reason, the deprecated API (addMToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addMToMatrix has been replaced by buildMassMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(GuideForceField)] buildMassMatrix not implemented: for compatibility reason, the deprecated API (addMToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addMToMatrix has been replaced by buildMassMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(CoilsForceField)] buildMassMatrix not implemented: for compatibility reason, the deprecated API (addMToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addMToMatrix has been replaced by buildMassMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(CatheterForceField)] buildDampingMatrix not implemented: for compatibility reason, the deprecated API (addBToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addBToMatrix has been replaced by buildDampingMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(GuideForceField)] buildDampingMatrix not implemented: for compatibility reason, the deprecated API (addBToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addBToMatrix has been replaced by buildDampingMatrix
[WARNING] [AdaptiveBeamForceFieldAndMass(CoilsForceField)] buildDampingMatrix not implemented: for compatibility reason, the deprecated API (addBToMatrix) will be used. This compatibility will disapear in the future, and will cause issues in simulations. Please update the code of AdaptiveBeamForceFieldAndMass to ensure right behavior: the function addBToMatrix has been replaced by buildDampingMatrix
[ERROR]   [SofaRuntime] Fault: <Fault 1: "<class '_queue.Empty'>:">
Traceback (most recent call last):
  File "E:\Anaconda3\envs\sofarl\lib\site-packages\SofaGW\simulation/SimClient.py", line 116, in <module>
    simmanager.getorder()
  File "E:\Anaconda3\envs\sofarl\lib\site-packages\SofaGW\simulation/SimClient.py", line 49, in getorder
    self.orderdict = self.client.dataget()
  File "E:\Anaconda3\envs\sofarl\lib\site-packages\SofaGW\simulation/SimClient.py", line 29, in dataget
    return self.server.serverget()
  File "E:\Anaconda3\envs\sofarl\lib\xmlrpc\client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "E:\Anaconda3\envs\sofarl\lib\xmlrpc\client.py", line 1450, in __request
    response = self.__transport.request(
  File "E:\Anaconda3\envs\sofarl\lib\xmlrpc\client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "E:\Anaconda3\envs\sofarl\lib\xmlrpc\client.py", line 1169, in single_request
    return self.parse_response(resp)
  File "E:\Anaconda3\envs\sofarl\lib\xmlrpc\client.py", line 1341, in parse_response
    return u.close()
  File "E:\Anaconda3\envs\sofarl\lib\xmlrpc\client.py", line 655, in close
    raise Fault(**self._stack[0])

Exception in thread Thread-6:
Traceback (most recent call last):
  File "E:\Anaconda3\envs\sofarl\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Anaconda3\envs\sofarl\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Anaconda3\envs\sofarl\lib\site-packages\SofaGW\simulation\SimServer.py", line 101, in deferredStart
    subprocess.run([sys.executable, path, str(port_rpc), vessel_filename, commu_dir],
  File "E:\Anaconda3\envs\sofarl\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['E:\\Anaconda3\\envs\\sofarl\\python.exe', 'E:\\Anaconda3\\envs\\sofarl\\lib\\site-packages\\SofaGW\\simulation/SimClient.py', '49622', 'C:\\Users\\YTL\\vessel\\phantom.obj', 'E:\\Anaconda3\\envs\\sofarl\\lib\\site-packages\\SofaGW/_cache_']' returned non-zero exit status 1.
```

2. The latest version (July, 2024)
![image](https://github.com/user-attachments/assets/16728fa1-2a49-413f-bbd5-9ffc514edec2)

**Comment by candi4** [comment]
OK, I got it.

1. **You are not doing anything with the simulation.** It's the reason of the error.
The `SofaGW` package runs two Python scripts that communicate with each other. I set a time limit for which the code waits for a response, as the parameter `timeout`. If you don't do anything, they waits and returns error as I set.
The `SofaGW` package runs two Python scripts that communicate with each other. I set a `timeout` parameter to define how long the code waits for a response. If no method is used within this time, the code will return an error as configured.

2. **You didn't check the directory of the vessel file.**
Simply use this method to check the installation as described in the README.
    ```python
    import SofaGW
    SofaGW.test_installation()
    ```

**Comment by Metaphysicist0** [comment]
Sorry, I've tried, but the situation remains unchanged:

1. The command prompt is frozen, and I'm unable to input any commands.
2. The simulation animation appears normally, just like the given GIF.
3. Additionally, I've checked the installation status of the SOFA library, and it seems normal, just as described in the readme.
```
Checking SOFA_ROOT and SOFAPYTHON3_ROOT
Using environment variable SOFA_ROOT: G:\SOFA_v23.06.00_Win64
Warning: environment variable SOFAPYTHON3_ROOT is empty. Trying to guess it.
Guessed SOFAPYTHON3_ROOT: G:\SOFA_v23.06.00_Win64\plugins\SofaPython3
Found Sofa.Helper.dll in G:\SOFA_v23.06.00_Win64\bin
Found SofaPython3.dll in G:\SOFA_v23.06.00_Win64\plugins\SofaPython3\bin
```
4.  The directory paths for the vessel files have been set to absolute paths in files like Simserver.py, scene.py, etc.

**Comment by candi4** [comment]
You have to write python script. I think you are trying to write something in the prompt. Please refer to [example.py](https://github.com/candi4/SofaGuidewireNav/blob/main/example.py).

**Comment by Metaphysicist0** [comment]
Thank you very much for your patience and assistance! The problem has been resolved, and I am now able to get started with the prompt.
